# Generated by Django 6.0.7 on 2026-07-25 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_evendedor_alter_usuario_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='tipo',
            new_name='cep',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='eVendedor',
            new_name='is_vendedor',
        ),
    ]
