# Generated by Django 6.0.7 on 2026-07-28 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('produto', 'Desconto sobre produto'), ('frete', 'Desconto sobre frete')], max_length=10)),
                ('desconto_percentual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('valor_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('limite_usos', models.PositiveIntegerField(blank=True, null=True)),
                ('usos_atuais', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
